FROM debian:bookworm

# install development libraries
RUN apt update \
	# install required shit
	# npx because we love vibe coding
	&& apt install -y \
	cppzmq-dev \
	socat \
	screen \
	nodejs \
    npm
